In [5]:
import pandas as pd
population = pd.read_csv("/Users/OwenBarberie/Desktop/GSB_544/pop.csv")
df

          country   1800   1801   1802   1803  ...   2096   2097   2098   2099   2100
0     Afghanistan  3.28M  3.28M  3.28M  3.28M  ...   128M   128M   129M   130M   130M
1          Angola  1.57M  1.57M  1.57M  1.57M  ...   145M   147M   148M   149M   150M
2         Albania   400k   402k   404k   405k  ...  1.25M  1.23M  1.22M   1.2M  1.18M
3         Andorra   2650   2650   2650   2650  ...  49.6k    49k  48.4k  47.8k  47.2k
4             UAE  40.2k  40.2k  40.2k  40.2k  ...  25.2M  25.4M  25.7M  25.9M  26.1M
..            ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
192         Samoa  47.3k  47.3k  47.3k  47.3k  ...   378k   380k   381k   382k   384k
193         Yemen  2.59M  2.59M  2.59M  2.59M  ...   109M   109M   109M   110M   110M
194  South Africa  1.45M  1.45M  1.46M  1.46M  ...  93.5M  93.7M  93.9M  94.1M  94.3M
195        Zambia   747k   758k   770k   782k  ...  63.1M  63.4M  63.8M  64.1M  64.5M
196      Zimbabwe  1.09M  1.09M  1.09M  1.09M  ...  36.8M  36.9M    37M  37.1M  37.2M

[197 rows x 302 columns]

In [8]:
long_population = population.melt(id_vars=["country"], var_name="year", value_name="population")
# id_vars says what column you want to keep
long_population

            country  year population
0       Afghanistan  1800      3.28M
1            Angola  1800      1.57M
2           Albania  1800       400k
3           Andorra  1800       2650
4               UAE  1800      40.2k
...             ...   ...        ...
59292         Samoa  2100       384k
59293         Yemen  2100       110M
59294  South Africa  2100      94.3M
59295        Zambia  2100      64.5M
59296      Zimbabwe  2100      37.2M

[59297 rows x 3 columns]

In [9]:
data_dir = "http://dlsun.github.io/pods/data/names/"
names1995 = pd.read_csv(data_dir + "yob1995.txt",
                        header=None,
                        names=["Name", "Sex", "Count"])
names1995

           Name Sex  Count
0       Jessica   F  27935
1        Ashley   F  26603
2         Emily   F  24378
3      Samantha   F  21646
4         Sarah   F  21369
...         ...  ..    ...
26075     Zerek   M      5
26076      Zhen   M      5
26077     Ziggy   M      5
26078    Zuberi   M      5
26079      Zyon   M      5

[26080 rows x 3 columns]